version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: qualitycare
      MYSQL_USER: temp
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/scripts/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./src/scripts/02-dummy_data.sql:/docker-entrypoint-initdb.d/02-dummy_data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    command: npm run dev

volumes:
  db_data:
