version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password  # Replace with a strong password
      MYSQL_DATABASE: qualitycare # Replace with your database name
      MYSQL_USER: temp # Replace with your database user
      MYSQL_PASSWORD: password # Replace with your database password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: . # Assumes your Dockerfile is in the same directory as docker-compose.yml
      dockerfile: Dockerfile # Name of your Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001" # Expose the Node.js app port
    depends_on:
      - mysql
    command: npm run dev

volumes:
  db_data: